# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a7ae77afb54727e565e2a1a6cb16444b42dd9afff5b534e5ea6c3534362568135171fc5b4fdfcc13255714a250790bf17afda582845e781b9a44fb1497d273c

test:
  secret_key_base: 4bc8b602a3137478e845ff2cb380f0d780d489638996dafa83c9b0dce7d08bc52c7fe447bc9fb7a75f197a54278b3e7b4ffdddb2eafe39342e2d08f652db9da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
